### ISSUE TITLE
Decompiling Python files

### ISSUE THREAD

**Issue by BROTOKARMOKAR** [Ezz-Kun/deob-bs#1]
@Ezz-Kun Bro Please make a tool about Decompiling Python files

Like Pyc to Py ( which has uncompyle6 error )

**Comment by Ezz-Kun** [comment]
> @Ezz-Kun Bro Please make a tool about Decompiling Python files
> 
> Like Pyc to Py ( which has uncompyle6 error )

What kind of error? try to include a screenshot or error text

**Comment by htr-tech** [comment]
#### Here Is the ss !!

![image](https://user-images.githubusercontent.com/56682134/82537923-b396d000-9b6c-11ea-91a7-f3e94e9856c6.png)

**Comment by BROTOKARMOKAR** [comment]
Here is the ss 
![image](https://user-images.githubusercontent.com/58427672/82538313-61a27a00-9b6d-11ea-842e-ae1b62989dd1.png)

**Comment by BROTOKARMOKAR** [comment]
@Ezz-Kun Sir Why Uncompyle6 is showing such error ???

![image](https://user-images.githubusercontent.com/58427672/83233420-7bb50b80-a1b0-11ea-9d7a-a92ae5fdcc7f.png)

Please give me a Fix . Please  😢😢😢😢

**Comment by Ezz-Kun** [comment]
> @Ezz-Kun Sir Why Uncompyle6 is showing such error ???
> 
> ![image](https://user-images.githubusercontent.com/58427672/83233420-7bb50b80-a1b0-11ea-9d7a-a92ae5fdcc7f.png)
> 
> Please give me a Fix . Please

try using Decompyle++ 
[In this (pycdc)](https://github.com/zrax/pycdc)

**Comment by BROTOKARMOKAR** [comment]
@Ezz-Kun sir now ???

![1](https://user-images.githubusercontent.com/58427672/83318386-321efc00-a256-11ea-9e1d-5cffacb9dbd7.PNG)![2](https://user-images.githubusercontent.com/58427672/83318387-34815600-a256-11ea-860f-8ac97c7d62ba.PNG)

I am a newbie in this sector .Plz help 😢 😞

**Comment by Ezz-Kun** [comment]
> @Ezz-Kun sir now ???
> 
> ![1](https://user-images.githubusercontent.com/58427672/83318386-321efc00-a256-11ea-9e1d-5cffacb9dbd7.PNG)![2](https://user-images.githubusercontent.com/58427672/83318387-34815600-a256-11ea-860f-8ac97c7d62ba.PNG)
> 
> I am a newbie in this sector .Plz help

It's easy, just make Google your friend and start searching for what you don't understand! :), Use Your Brain
